site_author: Ampify Authors
site_description: Help Create Weapons of Mass Construction!
site_license: This work has been placed into the Public Domain.
site_title: Ampify Blog
site_url: http://blog.ampify.it

analytics_id: UA-90176-25
section_id: blog
typekit: enabled

index_pages:
- archive.html: archive.genshi
- feed.rss: feed.genshi
- index.html: index.genshi
